"""
Complete KBS standardized field mappings.
Contains all 162 pre-defined field mappings for KBS financial data.
"""

# Complete standardized mappings for KBS financial fields
KBS_COMPLETE_MAPPINGS = {
  "1": {
    "original_vi": "1. Thu nhập lãi và các khoản thu nhập tương tự",
    "original_en": "1. Interest income and similar income",
    "snake_case": "thu_nhap_lai_va_cac_khoan_thu_nhap_tuong_tu",
    "base_name": "thu_nhap_lai_va_cac_khoan_thu_nhap_tuong_tu",
    "was_conflict": False,
    "was_standardized": False,
  },
  "19": {
    "original_vi": "8. Chi phí thuế TNDN hoãn lại",
    "original_en": "8. Deferred income tax expenses (*)",
    "snake_case": "deferred_income_tax_expense",
    "base_name": "deferred_income_tax_expense",
    "was_conflict": False,
    "was_standardized": False,
  },
  "21": {
    "original_vi": "XIII. Lợi nhuận sau thuế (XI-XII)",
    "original_en": "XIII. Net profit after tax",
    "snake_case": "xiii_loi_nhuan_sau_thue_xixii",
    "base_name": "xiii_loi_nhuan_sau_thue_xixii",
    "was_conflict": False,
    "was_standardized": False,
  },
  "22": {
    "original_vi": "XIV. Lợi ích của cổ đông thiểu số",
    "original_en": "XIV. Minority interest",
    "snake_case": "xiv_loi_ich_cua_co_dong_thieu_so",
    "base_name": "xiv_loi_ich_cua_co_dong_thieu_so",
    "was_conflict": False,
    "was_standardized": False,
  },
  "23": {
    "original_vi": "XV. Lợi nhuận sau thuế của cổ đông của Ngân hàng mẹ (XIII-XIV)",
    "original_en": "XV. Net profit atttributable to the equity holders of the Bank ",
    "snake_case": "xv_loi_nhuan_sau_thue_cua_co_dong_cua_ngan_hang_me_xiiixiv",
    "base_name": "xv_loi_nhuan_sau_thue_cua_co_dong_cua_ngan_hang_me_xiiixiv",
    "was_conflict": False,
    "was_standardized": False,
  },
  "24": {
    "original_vi": "Lãi cơ bản trên cổ phiếu (BCTC) (VNÐ)",
    "original_en": "Earning per share (VND)",
    "snake_case": "lai_co_ban_tren_co_phieu_bctc_vnð",
    "base_name": "lai_co_ban_tren_co_phieu_bctc_vnð",
    "was_conflict": False,
    "was_standardized": False,
  },
  "25": {
    "original_vi": "3. Đầu tư dài hạn khác",
    "original_en": "3. Other long-term investments",
    "snake_case": "other_long_term_investments",
    "base_name": "other_long_term_investments",
    "was_conflict": False,
    "was_standardized": False,
  },
  "26": {
    "original_vi": "4. Dự phòng giảm giá đầu tư dài hạn ",
    "original_en": "4. Provision for diminution in value of long-term investments ",
    "snake_case": "investment_provision",
    "base_name": "investment_provision",
    "was_conflict": False,
    "was_standardized": False,
  },
  "27": {
    "original_vi": "X. Tài sản cố định",
    "original_en": "X. Fixed assets",
    "snake_case": "x_tai_san_co_dinh",
    "base_name": "x_tai_san_co_dinh",
    "was_conflict": False,
    "was_standardized": False,
  },
  "28": {
    "original_vi": "1. Tài sản cố định hữu hình ",
    "original_en": "1. Tangible fixed assets",
    "snake_case": "tai_san_co_dinh_huu_hinh",
    "base_name": "tai_san_co_dinh_huu_hinh",
    "was_conflict": False,
    "was_standardized": False,
  },
  "29": {
    "original_vi": "a. Nguyên giá TSCĐ",
    "original_en": "a. Cost",
    "snake_case": "a_nguyen_gia_tscd",
    "base_name": "a_nguyen_gia_tscd",
    "was_conflict": False,
    "was_standardized": False,
  },
  "30": {
    "original_vi": "b. Hao mòn TSCĐ ",
    "original_en": "b. Accumulated depreciation",
    "snake_case": "b_hao_mon_tscd",
    "base_name": "b_hao_mon_tscd",
    "was_conflict": False,
    "was_standardized": False,
  },
  "31": {
    "original_vi": "2. Tài sản cố định thuê tài chính",
    "original_en": "2. Finance leased fixed assets",
    "snake_case": "finance_leased_fixed_assets",
    "base_name": "finance_leased_fixed_assets",
    "was_conflict": False,
    "was_standardized": False,
  },
  "32": {
    "original_vi": "a. Nguyên giá TSCĐ",
    "original_en": "a. Cost",
    "snake_case": "a_nguyen_gia_tscd_32",
    "base_name": "a_nguyen_gia_tscd",
    "was_conflict": True,
    "was_standardized": False,
  },
  "34": {
    "original_vi": "3. Tài sản cố định vô hình",
    "original_en": "3. Intangible fixed assets",
    "snake_case": "intangible_fixed_assets",
    "base_name": "intangible_fixed_assets",
    "was_conflict": False,
    "was_standardized": False,
  },
  "35": {
    "original_vi": "a. Nguyên giá TSCĐ",
    "original_en": "a. Cost",
    "snake_case": "a_nguyen_gia_tscd_35",
    "base_name": "a_nguyen_gia_tscd",
    "was_conflict": True,
    "was_standardized": False,
  },
  "2": {
    "original_vi": "2. Chi phí lãi và các chi phí tương tự",
    "original_en": "2. Interest expense and similar expenses",
    "snake_case": "chi_phi_lai_va_cac_chi_phi_tuong_tu",
    "base_name": "chi_phi_lai_va_cac_chi_phi_tuong_tu",
    "was_conflict": False,
    "was_standardized": False,
  },
  "20": {
    "original_vi": "XII. Chi phí thuế TNDN",
    "original_en": "XII. Corporate income tax ",
    "snake_case": "xii_chi_phi_thue_tndn",
    "base_name": "xii_chi_phi_thue_tndn",
    "was_conflict": False,
    "was_standardized": False,
  },
  "33": {
    "original_vi": "b. Hao mòn TSCĐ ",
    "original_en": "b. Accumulated depreciation",
    "snake_case": "b_hao_mon_tscd_33",
    "base_name": "b_hao_mon_tscd",
    "was_conflict": True,
    "was_standardized": False,
  },
  "18": {
    "original_vi": "7. Chi phí thuế TNDN hiện hành",
    "original_en": "7. Current corporate income tax expenses",
    "snake_case": "current_income_tax_expense",
    "base_name": "current_income_tax_expense",
    "was_conflict": False,
    "was_standardized": False,
  },
  "10": {
    "original_vi": "5. Thu nhập từ hoạt động khác",
    "original_en": "5. Other income",
    "snake_case": "thu_nhap_tu_hoat_dong_khac",
    "base_name": "thu_nhap_tu_hoat_dong_khac",
    "was_conflict": False,
    "was_standardized": False,
  },
  "17": {
    "original_vi": "XI. Tổng lợi nhuận trước thuế (IX-X)",
    "original_en": "XI. Profit before tax ",
    "snake_case": "xi_tong_loi_nhuan_truoc_thue_ixx",
    "base_name": "xi_tong_loi_nhuan_truoc_thue_ixx",
    "was_conflict": False,
    "was_standardized": False,
  },
  "5": {
    "original_vi": "4. Chi phí hoạt động dịch vụ",
    "original_en": "4. Fee and commission expenses",
    "snake_case": "fee_commission_expense",
    "base_name": "fee_commission_expense",
    "was_conflict": False,
    "was_standardized": False,
  },
  "6": {
    "original_vi": "II. Lãi/lỗ thuần từ hoạt động dịch vụ",
    "original_en": "II. Net fee and commission income ",
    "snake_case": "ii_lailo_thuan_tu_hoat_dong_dich_vu",
    "base_name": "ii_lailo_thuan_tu_hoat_dong_dich_vu",
    "was_conflict": False,
    "was_standardized": False,
  },
  "7": {
    "original_vi": "III. Lãi/lỗ thuần từ hoạt động kinh doanh ngoại hối và vàng",
    "original_en": "III. Net gain/(loss) from foreign currencies and gold trading",
    "snake_case": "iii_lailo_thuan_tu_hoat_dong_kinh_doanh_ngoai_hoi_va_vang",
    "base_name": "iii_lailo_thuan_tu_hoat_dong_kinh_doanh_ngoai_hoi_va_vang",
    "was_conflict": False,
    "was_standardized": False,
  },
  "8": {
    "original_vi": "IV. Lãi/lỗ thuần từ mua bán chứng khoán kinh doanh",
    "original_en": "IV. Net gain/(loss) from trading securities",
    "snake_case": "iv_lailo_thuan_tu_mua_ban_chung_khoan_kinh_doanh",
    "base_name": "iv_lailo_thuan_tu_mua_ban_chung_khoan_kinh_doanh",
    "was_conflict": False,
    "was_standardized": False,
  },
  "9": {
    "original_vi": "V. Lãi/lỗ thuần từ mua bán chứng khoán đầu tư",
    "original_en": "V. Net gain/(loss) from investment securities",
    "snake_case": "v_lailo_thuan_tu_mua_ban_chung_khoan_dau_tu",
    "base_name": "v_lailo_thuan_tu_mua_ban_chung_khoan_dau_tu",
    "was_conflict": False,
    "was_standardized": False,
  },
  "4": {
    "original_vi": "3. Thu nhập từ hoạt động dịch vụ",
    "original_en": "3. Fee and commission income",
    "snake_case": "thu_nhap_tu_hoat_dong_dich_vu",
    "base_name": "thu_nhap_tu_hoat_dong_dich_vu",
    "was_conflict": False,
    "was_standardized": False,
  },
  "11": {
    "original_vi": "6. Chi phí hoạt động khác",
    "original_en": "6. Other expenses",
    "snake_case": "chi_phi_hoat_dong_khac",
    "base_name": "chi_phi_hoat_dong_khac",
    "was_conflict": False,
    "was_standardized": False,
  },
  "15": {
    "original_vi": "IX. Lợi nhuận thuần từ hoạt động kinh doanh trước chi phí dự phòng rủi ro tín dụng (I+II+III+IV+V+VI+VII-VIII)",
    "original_en": "IX. Operating profit before provision for credit losses",
    "snake_case": "ix_loi_nhuan_thuan_tu_hoat_dong_kinh_doanh_truoc_chi_phi_du_phong_rui_ro_tin_dung_iiiiiiivvviviiviii",
    "base_name": "ix_loi_nhuan_thuan_tu_hoat_dong_kinh_doanh_truoc_chi_phi_du_phong_rui_ro_tin_dung_iiiiiiivvviviiviii",
    "was_conflict": False,
    "was_standardized": False,
  },
  "16": {
    "original_vi": "X. Chi phí dự phòng rủi ro tín dụng",
    "original_en": "X. Provision for credit losses",
    "snake_case": "x_chi_phi_du_phong_rui_ro_tin_dung",
    "base_name": "x_chi_phi_du_phong_rui_ro_tin_dung",
    "was_conflict": False,
    "was_standardized": False,
  },
  "12": {
    "original_vi": "VI. Lãi/lỗ thuần từ hoạt động khác",
    "original_en": "VI. Net other income ",
    "snake_case": "vi_lailo_thuan_tu_hoat_dong_khac",
    "base_name": "vi_lailo_thuan_tu_hoat_dong_khac",
    "was_conflict": False,
    "was_standardized": False,
  },
  "3": {
    "original_vi": "I. Thu nhập lãi thuần",
    "original_en": "I. Net interest income ",
    "snake_case": "i_thu_nhap_lai_thuan",
    "base_name": "i_thu_nhap_lai_thuan",
    "was_conflict": False,
    "was_standardized": False,
  },
  "14": {
    "original_vi": "VIII. Chi phí hoạt động",
    "original_en": "VIII. Operating expenses",
    "snake_case": "viii_chi_phi_hoat_dong",
    "base_name": "viii_chi_phi_hoat_dong",
    "was_conflict": False,
    "was_standardized": False,
  },
  "13": {
    "original_vi": "VII. Thu nhập từ góp vốn, mua cổ phần",
    "original_en": "VII. Income from capital contribution and long-term investments",
    "snake_case": "vii_thu_nhap_tu_gop_von_mua_co_phan",
    "base_name": "vii_thu_nhap_tu_gop_von_mua_co_phan",
    "was_conflict": False,
    "was_standardized": False,
  },
  "69": {
    "original_vi": "e. Cổ phiếu ưu đãi",
    "original_en": "e. Preferred stock",
    "snake_case": "e_co_phieu_uu_dai",
    "base_name": "e_co_phieu_uu_dai",
    "was_conflict": False,
    "was_standardized": False,
  },
  "83": {
    "original_vi": "22. Chi từ các quỹ của TCTD",
    "original_en": "22. Payments from reserves",
    "snake_case": "chi_tu_cac_quy_cua_tctd",
    "base_name": "chi_tu_cac_quy_cua_tctd",
    "was_conflict": False,
    "was_standardized": False,
  },
  "70": {
    "original_vi": "g. Vốn khác",
    "original_en": "g. Other capital",
    "snake_case": "g_von_khac",
    "base_name": "g_von_khac",
    "was_conflict": False,
    "was_standardized": False,
  },
  "71": {
    "original_vi": "2. Quỹ của TCTD",
    "original_en": "2. Reserves",
    "snake_case": "credit_institution_reserves",
    "base_name": "credit_institution_reserves",
    "was_conflict": False,
    "was_standardized": False,
  },
  "72": {
    "original_vi": "3. Chênh lệch tỷ giá hối đoái ",
    "original_en": "3. Foreign exchange differences ",
    "snake_case": "chenh_lech_ty_gia_hoi_doai",
    "base_name": "chenh_lech_ty_gia_hoi_doai",
    "was_conflict": False,
    "was_standardized": False,
  },
  "74": {
    "original_vi": "5. Lợi nhuận chưa phân phối/Lỗ lũy kế ",
    "original_en": "5. Undistributed earnings after tax/Accumulated loss ",
    "snake_case": "loi_nhuan_chua_phan_phoilo_luy_ke",
    "base_name": "loi_nhuan_chua_phan_phoilo_luy_ke",
    "was_conflict": False,
    "was_standardized": False,
  },
  "75": {
    "original_vi": "6. Lợi ích cổ đông không kiểm soát",
    "original_en": "6. Minority's interest",
    "snake_case": "non_controlling_interest",
    "base_name": "non_controlling_interest",
    "was_conflict": False,
    "was_standardized": False,
  },
  "76": {
    "original_vi": "IX. Lợi ích của cổ đông thiểu số",
    "original_en": "IX. Minority interest",
    "snake_case": "ix_loi_ich_cua_co_dong_thieu_so",
    "base_name": "ix_loi_ich_cua_co_dong_thieu_so",
    "was_conflict": False,
    "was_standardized": False,
  },
  "77": {
    "original_vi": "TỔNG NỢ PHẢI TRẢ VÀ VỐN CHỦ SỞ HỮU",
    "original_en": "TOTAL LIABILITIES AND OWNER'S EQUITY",
    "snake_case": "total_liabilities_equity",
    "base_name": "total_liabilities_equity",
    "was_conflict": False,
    "was_standardized": False,
  },
  "78": {
    "original_vi": "17. Tăng/(Giảm) tiền gửi của khách hàng (bao gồm cả Kho bạc Nhà nước)",
    "original_en": "17. Increase/(Decrease) in deposit from customers (Including The State Treasury)",
    "snake_case": "tanggiam_tien_gui_cua_khach_hang_bao_gom_ca_kho_bac_nha_nuoc",
    "base_name": "tanggiam_tien_gui_cua_khach_hang_bao_gom_ca_kho_bac_nha_nuoc",
    "was_conflict": False,
    "was_standardized": False,
  },
  "79": {
    "original_vi": "18. Tăng/(Giảm) phát hành giấy tờ có giá (ngoại trừ giấy tờ có giá phát hành được tình vào hoạt động tài chính)",
    "original_en": "18. Increase/(Decrease) in valuable papers issued (excluding valuable papers categorized under financing activities)",
    "snake_case": "tanggiam_phat_hanh_giay_to_co_gia_ngoai_tru_giay_to_co_gia_phat_hanh_duoc_tinh_vao_hoat_dong_tai_chinh",
    "base_name": "tanggiam_phat_hanh_giay_to_co_gia_ngoai_tru_giay_to_co_gia_phat_hanh_duoc_tinh_vao_hoat_dong_tai_chinh",
    "was_conflict": False,
    "was_standardized": False,
  },
  "80": {
    "original_vi": "19. Tăng/(Giảm) vốn tài trợ, ủy thác đầu tư, cho vay mà TCTD chịu rủi ro",
    "original_en": "19. Increase/(Decrease) in funds received from Government, institutions, investments on behalf of investors and syndicated loans of the Bank's risks",
    "snake_case": "tanggiam_von_tai_tro_uy_thac_dau_tu_cho_vay_ma_tctd_chiu_rui_ro",
    "base_name": "tanggiam_von_tai_tro_uy_thac_dau_tu_cho_vay_ma_tctd_chiu_rui_ro",
    "was_conflict": False,
    "was_standardized": False,
  },
  "81": {
    "original_vi": "20. Tăng/(Giảm) các công cụ tài chính phái sinh và các khoản nợ tài chính khác",
    "original_en": "20. Increase/(Decrease) in derivatives and other financial liabilities",
    "snake_case": "tanggiam_cac_cong_cu_tai_chinh_phai_sinh_va_cac_khoan_no_tai_chinh_khac",
    "base_name": "tanggiam_cac_cong_cu_tai_chinh_phai_sinh_va_cac_khoan_no_tai_chinh_khac",
    "was_conflict": False,
    "was_standardized": False,
  },
  "73": {
    "original_vi": "4. Chênh lệch đánh giá lại tài sản",
    "original_en": "4. Assets revaluation differences",
    "snake_case": "chenh_lech_danh_gia_lai_tai_san",
    "base_name": "chenh_lech_danh_gia_lai_tai_san",
    "was_conflict": False,
    "was_standardized": False,
  },
  "90": {
    "original_vi": "5. Tiền thu từ bán, thanh lý bất động sản đầu tư",
    "original_en": "5. Receipts from disposal of investment properties",
    "snake_case": "tien_thu_tu_ban_thanh_ly_bat_dong_san_dau_tu",
    "base_name": "tien_thu_tu_ban_thanh_ly_bat_dong_san_dau_tu",
    "was_conflict": False,
    "was_standardized": False,
  },
  "84": {
    "original_vi": "I - Lưu chuyển tiền thuần từ hoạt động kinh doanh ",
    "original_en": " Net cash flows from operating activities",
    "snake_case": "i_luu_chuyen_tien_thuan_tu_hoat_dong_kinh_doanh",
    "base_name": "i_luu_chuyen_tien_thuan_tu_hoat_dong_kinh_doanh",
    "was_conflict": False,
    "was_standardized": False,
  },
  "85": {
    "original_vi": "Lưu chuyển tiền từ hoạt động đầu tư",
    "original_en": "II. Cash flows from investing activities",
    "snake_case": "luu_chuyen_tien_tu_hoat_dong_dau_tu",
    "base_name": "luu_chuyen_tien_tu_hoat_dong_dau_tu",
    "was_conflict": False,
    "was_standardized": False,
  },
  "86": {
    "original_vi": "1. Mua sắm tài sản cố định ",
    "original_en": "1. Purchase of  fixed assets",
    "snake_case": "mua_sam_tai_san_co_dinh",
    "base_name": "mua_sam_tai_san_co_dinh",
    "was_conflict": False,
    "was_standardized": False,
  },
  "87": {
    "original_vi": "2. Tiền thu từ thanh lý, nhượng bán TSCĐ",
    "original_en": "2. Receipts from disposal of fixed assets",
    "snake_case": "tien_thu_tu_thanh_ly_nhuong_ban_tscd",
    "base_name": "tien_thu_tu_thanh_ly_nhuong_ban_tscd",
    "was_conflict": False,
    "was_standardized": False,
  },
  "88": {
    "original_vi": "3. Tiền chi từ thanh lý, nhượng bán TSCĐ ",
    "original_en": "3. Payments for disposal of fixed assets",
    "snake_case": "tien_chi_tu_thanh_ly_nhuong_ban_tscd",
    "base_name": "tien_chi_tu_thanh_ly_nhuong_ban_tscd",
    "was_conflict": False,
    "was_standardized": False,
  },
  "89": {
    "original_vi": "4. Mua sắm bất động sản đầu tư ",
    "original_en": "4. Purchase of investment properties",
    "snake_case": "mua_sam_bat_dong_san_dau_tu",
    "base_name": "mua_sam_bat_dong_san_dau_tu",
    "was_conflict": False,
    "was_standardized": False,
  },
  "91": {
    "original_vi": "6. Tiền chi ra do bán, thanh lý bất động sản đầu tư ",
    "original_en": "6. Payments for disposal of investment properties",
    "snake_case": "tien_chi_ra_do_ban_thanh_ly_bat_dong_san_dau_tu",
    "base_name": "tien_chi_ra_do_ban_thanh_ly_bat_dong_san_dau_tu",
    "was_conflict": False,
    "was_standardized": False,
  },
  "92": {
    "original_vi": "7. Tiền chi đầu tư, góp vốn vào các đơn vị khác (mua công ty con, góp vốn liên doanh, liên kết, đầu tư dài hạn khác)",
    "original_en": "7. Payments for investment in other entities",
    "snake_case": "tien_chi_dau_tu_gop_von_vao_cac_don_vi_khac_mua_cong_ty_con_gop_von_lien_doanh_lien_ket_dau_tu_dai_han_khac",
    "base_name": "tien_chi_dau_tu_gop_von_vao_cac_don_vi_khac_mua_cong_ty_con_gop_von_lien_doanh_lien_ket_dau_tu_dai_han_khac",
    "was_conflict": False,
    "was_standardized": False,
  },
  "93": {
    "original_vi": "8. Tiền thu đầu tư, góp vốn vào các đơn vị khác (bán, thanh lý Công ty con, góp vốn liên doanh,  liên kết, đầu tư dài hạn khác)",
    "original_en": "8. Collections on investment in other entities",
    "snake_case": "tien_thu_dau_tu_gop_von_vao_cac_don_vi_khac_ban_thanh_ly_cong_ty_con_gop_von_lien_doanh_lien_ket_dau_tu_dai_han_khac",
    "base_name": "tien_thu_dau_tu_gop_von_vao_cac_don_vi_khac_ban_thanh_ly_cong_ty_con_gop_von_lien_doanh_lien_ket_dau_tu_dai_han_khac",
    "was_conflict": False,
    "was_standardized": False,
  },
  "94": {
    "original_vi": "9. Tiền thu cổ tức và lợi nhuận được chia từ các khoản đầu tư, góp vốn dài hạn",
    "original_en": "9. Dividends and profit received",
    "snake_case": "tien_thu_co_tuc_va_loi_nhuan_duoc_chia_tu_cac_khoan_dau_tu_gop_von_dai_han",
    "base_name": "tien_thu_co_tuc_va_loi_nhuan_duoc_chia_tu_cac_khoan_dau_tu_gop_von_dai_han",
    "was_conflict": False,
    "was_standardized": False,
  },
  "95": {
    "original_vi": "II- Lưu chuyển tiền thuần từ hoạt động đầu tư",
    "original_en": "Net cash flows from investing activities",
    "snake_case": "ii_luu_chuyen_tien_thuan_tu_hoat_dong_dau_tu",
    "base_name": "ii_luu_chuyen_tien_thuan_tu_hoat_dong_dau_tu",
    "was_conflict": False,
    "was_standardized": False,
  },
  "96": {
    "original_vi": "Lưu chuyển tiền từ hoạt động tài chính",
    "original_en": "III. Cash flows from financing activities",
    "snake_case": "luu_chuyen_tien_tu_hoat_dong_tai_chinh",
    "base_name": "luu_chuyen_tien_tu_hoat_dong_tai_chinh",
    "was_conflict": False,
    "was_standardized": False,
  },
  "97": {
    "original_vi": "1. Tăng vốn cổ phần từ góp vốn và/hoặc phát hành cổ phiếu",
    "original_en": "1. Receipts from equity issue and owner's capital contribution",
    "snake_case": "tang_von_co_phan_tu_gop_von_vahoac_phat_hanh_co_phieu",
    "base_name": "tang_von_co_phan_tu_gop_von_vahoac_phat_hanh_co_phieu",
    "was_conflict": False,
    "was_standardized": False,
  },
  "67": {
    "original_vi": "c. Thặng dư vốn cổ phần",
    "original_en": "c. Share premium",
    "snake_case": "c_thang_du_von_co_phan",
    "base_name": "c_thang_du_von_co_phan",
    "was_conflict": False,
    "was_standardized": False,
  },
  "68": {
    "original_vi": "d. Cổ phiếu quỹ ",
    "original_en": "d. Treasury shares ",
    "snake_case": "d_co_phieu_quy",
    "base_name": "d_co_phieu_quy",
    "was_conflict": False,
    "was_standardized": False,
  },
  "82": {
    "original_vi": "21. Tăng/(Giảm) khác về công nợ hoạt động",
    "original_en": "21. Increase/(Decrease) in other operating liabilities",
    "snake_case": "tanggiam_khac_ve_cong_no_hoat_dong",
    "base_name": "tanggiam_khac_ve_cong_no_hoat_dong",
    "was_conflict": False,
    "was_standardized": False,
  },
  "66": {
    "original_vi": "b. Vốn đầu tư XDCB",
    "original_en": "b. Reserves for investments in construction",
    "snake_case": "b_von_dau_tu_xdcb",
    "base_name": "b_von_dau_tu_xdcb",
    "was_conflict": False,
    "was_standardized": False,
  },
  "50": {
    "original_vi": "II. Tiền gửi và vay các TCTD khác",
    "original_en": "II. Placements and borrowings from other credit institutions",
    "snake_case": "ii_tien_gui_va_vay_cac_tctd_khac",
    "base_name": "ii_tien_gui_va_vay_cac_tctd_khac",
    "was_conflict": False,
    "was_standardized": False,
  },
  "36": {
    "original_vi": "b. Hao mòn TSCĐ ",
    "original_en": "b. Accumulated depreciation",
    "snake_case": "b_hao_mon_tscd_36",
    "base_name": "b_hao_mon_tscd",
    "was_conflict": True,
    "was_standardized": False,
  },
  "37": {
    "original_vi": "XI. Bất động sản đầu tư",
    "original_en": "XI. Investment properties",
    "snake_case": "xi_bat_dong_san_dau_tu",
    "base_name": "xi_bat_dong_san_dau_tu",
    "was_conflict": False,
    "was_standardized": False,
  },
  "38": {
    "original_vi": "a. Nguyên giá BĐSĐT",
    "original_en": "a. Cost",
    "snake_case": "a_nguyen_gia_bdsdt",
    "base_name": "a_nguyen_gia_bdsdt",
    "was_conflict": False,
    "was_standardized": False,
  },
  "39": {
    "original_vi": "b. Hao mòn BĐSĐT ",
    "original_en": "b. Accumulated depreciation",
    "snake_case": "b_hao_mon_bdsdt",
    "base_name": "b_hao_mon_bdsdt",
    "was_conflict": False,
    "was_standardized": False,
  },
  "40": {
    "original_vi": "XII. Tài sản \"Có\" khác",
    "original_en": "XII. Other assets",
    "snake_case": "xii_tai_san_co_khac",
    "base_name": "xii_tai_san_co_khac",
    "was_conflict": False,
    "was_standardized": False,
  },
  "41": {
    "original_vi": "1. Các khoản phải thu",
    "original_en": "1.  Accounts receivables",
    "snake_case": "accounts_receivable",
    "base_name": "accounts_receivable",
    "was_conflict": False,
    "was_standardized": False,
  },
  "43": {
    "original_vi": "3. Tài sản thuế TNDN hoãn lại",
    "original_en": "3. Deferred income tax assets",
    "snake_case": "deferred_tax_assets",
    "base_name": "deferred_tax_assets",
    "was_conflict": False,
    "was_standardized": False,
  },
  "44": {
    "original_vi": "4. Tài sản Có khác",
    "original_en": "4. Other assets",
    "snake_case": "other_assets",
    "base_name": "other_assets",
    "was_conflict": False,
    "was_standardized": False,
  },
  "45": {
    "original_vi": "   - Trong đó: Lợi thế thương mại",
    "original_en": "   - Of which: Goodwill",
    "snake_case": "trong_do_loi_the_thuong_mai",
    "base_name": "trong_do_loi_the_thuong_mai",
    "was_conflict": False,
    "was_standardized": False,
  },
  "46": {
    "original_vi": "5. Các khoản dự phòng rủi ro cho các tài sản Có nội bảng khác ",
    "original_en": "5. Provisions for risks in other assets ",
    "snake_case": "cac_khoan_du_phong_rui_ro_cho_cac_tai_san_co_noi_bang_khac",
    "base_name": "cac_khoan_du_phong_rui_ro_cho_cac_tai_san_co_noi_bang_khac",
    "was_conflict": False,
    "was_standardized": False,
  },
  "47": {
    "original_vi": "TỔNG CỘNG TÀI SẢN",
    "original_en": "TOTAL ASSETS ",
    "snake_case": "total_assets",
    "base_name": "total_assets",
    "was_conflict": False,
    "was_standardized": False,
  },
  "48": {
    "original_vi": "B. NỢ PHẢI TRẢ VÀ VỐN CHỦ SỞ HỮU",
    "original_en": "B. LIABILITIES AND OWNER'S EQUITY",
    "snake_case": "b_no_phai_tra_va_von_chu_so_huu",
    "base_name": "b_no_phai_tra_va_von_chu_so_huu",
    "was_conflict": False,
    "was_standardized": False,
  },
  "49": {
    "original_vi": "I. Các khoản nợ Chính phủ và NHNN",
    "original_en": "I. Due to Government and borrowings from the State Bank of Vietnam",
    "snake_case": "i_cac_khoan_no_chinh_phu_va_nhnn",
    "base_name": "i_cac_khoan_no_chinh_phu_va_nhnn",
    "was_conflict": False,
    "was_standardized": False,
  },
  "42": {
    "original_vi": "2. Các khoản lãi, phí phải thu",
    "original_en": "2. Interest and fee receivables",
    "snake_case": "interest_receivable",
    "base_name": "interest_receivable",
    "was_conflict": False,
    "was_standardized": False,
  },
  "51": {
    "original_vi": "1. Tiền gửi của các TCTD khác",
    "original_en": "1. Placements from other credit institutions",
    "snake_case": "tien_gui_cua_cac_tctd_khac",
    "base_name": "tien_gui_cua_cac_tctd_khac",
    "was_conflict": False,
    "was_standardized": False,
  },
  "59": {
    "original_vi": "2. Thuế TNDN hoãn lại phải trả ",
    "original_en": "2. Deferred income tax liabilities",
    "snake_case": "deferred_tax_liabilities",
    "base_name": "deferred_tax_liabilities",
    "was_conflict": False,
    "was_standardized": False,
  },
  "52": {
    "original_vi": "2. Vay các TCTD khác",
    "original_en": "2. Borrowings from other credit institutions",
    "snake_case": "other_credit_institution_borrowings",
    "base_name": "other_credit_institution_borrowings",
    "was_conflict": False,
    "was_standardized": False,
  },
  "64": {
    "original_vi": "1. Vốn của TCTD",
    "original_en": "1. Capital",
    "snake_case": "credit_institution_capital",
    "base_name": "credit_institution_capital",
    "was_conflict": False,
    "was_standardized": False,
  },
  "63": {
    "original_vi": "VIII. Vốn và các quỹ",
    "original_en": "VIII. Capital and Reserves",
    "snake_case": "viii_von_va_cac_quy",
    "base_name": "viii_von_va_cac_quy",
    "was_conflict": False,
    "was_standardized": False,
  },
  "62": {
    "original_vi": "TỔNG NỢ PHẢI TRẢ",
    "original_en": "TOTAL LIABILITIES",
    "snake_case": "total_liabilities",
    "base_name": "total_liabilities",
    "was_conflict": False,
    "was_standardized": False,
  },
  "61": {
    "original_vi": "4. Dự phòng rủi ro khác (Dự phòng cho công nợ tiềm ẩn và cam kết ngoại bảng)",
    "original_en": "4. Provisions for contingent liabilities and off-balance sheet commitments",
    "snake_case": "du_phong_rui_ro_khac_du_phong_cho_cong_no_tiem_an_va_cam_ket_ngoai_bang",
    "base_name": "du_phong_rui_ro_khac_du_phong_cho_cong_no_tiem_an_va_cam_ket_ngoai_bang",
    "was_conflict": False,
    "was_standardized": False,
  },
  "60": {
    "original_vi": "3. Các khoản phải trả và công nợ khác",
    "original_en": "3. Other liabilities",
    "snake_case": "cac_khoan_phai_tra_va_cong_no_khac",
    "base_name": "cac_khoan_phai_tra_va_cong_no_khac",
    "was_conflict": False,
    "was_standardized": False,
  },
  "65": {
    "original_vi": "a. Vốn điều lệ",
    "original_en": "a. Charter capital",
    "snake_case": "a_von_dieu_le",
    "base_name": "a_von_dieu_le",
    "was_conflict": False,
    "was_standardized": False,
  },
  "57": {
    "original_vi": "VII. Các khoản nợ khác",
    "original_en": "VII. Other liabilities",
    "snake_case": "vii_cac_khoan_no_khac",
    "base_name": "vii_cac_khoan_no_khac",
    "was_conflict": False,
    "was_standardized": False,
  },
  "56": {
    "original_vi": "VI. Phát hành giấy tờ có giá",
    "original_en": "VI. Valuable papers (e.g. bonds, CDs..)",
    "snake_case": "vi_phat_hanh_giay_to_co_gia",
    "base_name": "vi_phat_hanh_giay_to_co_gia",
    "was_conflict": False,
    "was_standardized": False,
  },
  "55": {
    "original_vi": "V. Vốn tài trợ, ủy thác đầu tư, cho vay mà TCTD chịu rủi ro",
    "original_en": "V. Funds received from Government and institutions, investments on behalf of investors, syndicated loans of the Bank's risks",
    "snake_case": "v_von_tai_tro_uy_thac_dau_tu_cho_vay_ma_tctd_chiu_rui_ro",
    "base_name": "v_von_tai_tro_uy_thac_dau_tu_cho_vay_ma_tctd_chiu_rui_ro",
    "was_conflict": False,
    "was_standardized": False,
  },
  "54": {
    "original_vi": "IV. Các công cụ tài chính phái sinh và các khoản nợ tài chính khác",
    "original_en": "IV. Derivatives and other financial liabilities",
    "snake_case": "iv_cac_cong_cu_tai_chinh_phai_sinh_va_cac_khoan_no_tai_chinh_khac",
    "base_name": "iv_cac_cong_cu_tai_chinh_phai_sinh_va_cac_khoan_no_tai_chinh_khac",
    "was_conflict": False,
    "was_standardized": False,
  },
  "53": {
    "original_vi": "III. Tiền gửi của khách hàng",
    "original_en": "III. Deposits from customers",
    "snake_case": "iii_tien_gui_cua_khach_hang",
    "base_name": "iii_tien_gui_cua_khach_hang",
    "was_conflict": False,
    "was_standardized": False,
  },
  "58": {
    "original_vi": "1. Các khoản lãi, phí phải trả",
    "original_en": "1. Interest and fee payables",
    "snake_case": "cac_khoan_lai_phi_phai_tra",
    "base_name": "cac_khoan_lai_phi_phai_tra",
    "was_conflict": False,
    "was_standardized": False,
  },
  "104": {
    "original_vi": "IV- Lưu chuyển tiền thuần trong kỳ",
    "original_en": "Net cash flows during the period",
    "snake_case": "iv_luu_chuyen_tien_thuan_trong_ky",
    "base_name": "iv_luu_chuyen_tien_thuan_trong_ky",
    "was_conflict": False,
    "was_standardized": False,
  },
  "103": {
    "original_vi": "III- Lưu chuyển tiền thuần từ hoạt động tài chính",
    "original_en": "Net cash flows from financing activities",
    "snake_case": "iii_luu_chuyen_tien_thuan_tu_hoat_dong_tai_chinh",
    "base_name": "iii_luu_chuyen_tien_thuan_tu_hoat_dong_tai_chinh",
    "was_conflict": False,
    "was_standardized": False,
  },
  "107": {
    "original_vi": "VII. Tiền và các khoản tương đương tiền tại thời điểm cuối kỳ",
    "original_en": "Cash and cash equivalents at end of the period",
    "snake_case": "vii_tien_va_cac_khoan_tuong_duong_tien_tai_thoi_diem_cuoi_ky",
    "base_name": "vii_tien_va_cac_khoan_tuong_duong_tien_tai_thoi_diem_cuoi_ky",
    "was_conflict": False,
    "was_standardized": False,
  },
  "106": {
    "original_vi": "VI- Điều chỉnh ảnh hưởng của thay đổi tỷ giá",
    "original_en": "Exchange difference due to re-valuation of ending balances",
    "snake_case": "vi_dieu_chinh_anh_huong_cua_thay_doi_ty_gia",
    "base_name": "vi_dieu_chinh_anh_huong_cua_thay_doi_ty_gia",
    "was_conflict": False,
    "was_standardized": False,
  },
  "105": {
    "original_vi": "V- Tiền và các khoản tương đương tiền tại thời điểm đầu kỳ",
    "original_en": "Cash and cash equivalents at beginning of the period",
    "snake_case": "v_tien_va_cac_khoan_tuong_duong_tien_tai_thoi_diem_dau_ky",
    "base_name": "v_tien_va_cac_khoan_tuong_duong_tien_tai_thoi_diem_dau_ky",
    "was_conflict": False,
    "was_standardized": False,
  },
  "99": {
    "original_vi": "3. Tiền chi thanh toán giấy tờ có giá dài hạn có đủ điều kiện tính vào vốn tự có và các khoản vốn vay dài hạn khác ",
    "original_en": "3. Payments for issue of valuable papers qualified as owner's capital and other long-term borrowings",
    "snake_case": "tien_chi_thanh_toan_giay_to_co_gia_dai_han_co_du_dieu_kien_tinh_vao_von_tu_co_va_cac_khoan_von_vay_dai_han_khac",
    "base_name": "tien_chi_thanh_toan_giay_to_co_gia_dai_han_co_du_dieu_kien_tinh_vao_von_tu_co_va_cac_khoan_von_vay_dai_han_khac",
    "was_conflict": False,
    "was_standardized": False,
  },
  "102": {
    "original_vi": "6. Tiền thu được do bán cổ phiếu quỹ",
    "original_en": "6. Receipts from disposal of treasury shares",
    "snake_case": "tien_thu_duoc_do_ban_co_phieu_quy",
    "base_name": "tien_thu_duoc_do_ban_co_phieu_quy",
    "was_conflict": False,
    "was_standardized": False,
  },
  "101": {
    "original_vi": "5. Tiền chi ra mua cổ phiếu quỹ ",
    "original_en": "5. Payments for purchase of treasury shares",
    "snake_case": "tien_chi_ra_mua_co_phieu_quy",
    "base_name": "tien_chi_ra_mua_co_phieu_quy",
    "was_conflict": False,
    "was_standardized": False,
  },
  "100": {
    "original_vi": "4. Cổ tức trả cho cổ đông, lợi nhuận đã chia ",
    "original_en": "4. Dividends paid, profits distributed to owners",
    "snake_case": "co_tuc_tra_cho_co_dong_loi_nhuan_da_chia",
    "base_name": "co_tuc_tra_cho_co_dong_loi_nhuan_da_chia",
    "was_conflict": False,
    "was_standardized": False,
  },
  "98": {
    "original_vi": "2. Tiền thu từ phát hành giấy tờ có giá dài hạn có đủ điều kiện tính vào vốn tự có và các khoản vốn vay dài hạn khác",
    "original_en": "2. Receipts from issue of valuable papers qualified as owner's capital and other long-term borrowings",
    "snake_case": "tien_thu_tu_phat_hanh_giay_to_co_gia_dai_han_co_du_dieu_kien_tinh_vao_von_tu_co_va_cac_khoan_von_vay_dai_han_khac",
    "base_name": "tien_thu_tu_phat_hanh_giay_to_co_gia_dai_han_co_du_dieu_kien_tinh_vao_von_tu_co_va_cac_khoan_von_vay_dai_han_khac",
    "was_conflict": False,
    "was_standardized": False,
  },
  "124": {
    "original_vi": "TỔNG CỘNG NGUỒN VỐN",
    "original_en": "TOTAL OWNER'S EQUITY AND LIABILITIES ",
    "snake_case": "tong_cong_nguon_von",
    "base_name": "tong_cong_nguon_von",
    "was_conflict": False,
    "was_standardized": False,
  },
  "123": {
    "original_vi": "C. LỢI ÍCH CỔ ĐÔNG THIỂU SỐ",
    "original_en": "C. MINORITY'S INTEREST",
    "snake_case": "c_loi_ich_co_dong_thieu_so",
    "base_name": "c_loi_ich_co_dong_thieu_so",
    "was_conflict": False,
    "was_standardized": False,
  },
  "122": {
    "original_vi": "2. Nguồn kinh phí đã hình thành TSCĐ",
    "original_en": "2. Funds invested in fixed assets",
    "snake_case": "nguon_kinh_phi_da_hinh_thanh_tscd",
    "base_name": "nguon_kinh_phi_da_hinh_thanh_tscd",
    "was_conflict": False,
    "was_standardized": False,
  },
  "121": {
    "original_vi": "1. Nguồn kinh phí",
    "original_en": "1. Subsidized not-for-profit funds",
    "snake_case": "nguon_kinh_phi",
    "base_name": "nguon_kinh_phi",
    "was_conflict": False,
    "was_standardized": False,
  },
  "120": {
    "original_vi": "II. Nguồn kinh phí và quỹ khác",
    "original_en": "II. Other resources and funds ",
    "snake_case": "ii_nguon_kinh_phi_va_quy_khac",
    "base_name": "ii_nguon_kinh_phi_va_quy_khac",
    "was_conflict": False,
    "was_standardized": False,
  },
  "119": {
    "original_vi": "14. Quỹ dự phòng tài chính",
    "original_en": "14. Financial reserves",
    "snake_case": "quy_du_phong_tai_chinh",
    "base_name": "quy_du_phong_tai_chinh",
    "was_conflict": False,
    "was_standardized": False,
  },
  "118": {
    "original_vi": "13. Lợi ích cổ đông không kiểm soát",
    "original_en": "13. Minority's interest",
    "snake_case": "non_controlling_interest_118",
    "base_name": "non_controlling_interest",
    "was_conflict": True,
    "was_standardized": False,
  },
  "117": {
    "original_vi": "12. Nguồn vốn đầu tư XDCB",
    "original_en": "12. Reserves for investment in construction",
    "snake_case": "nguon_von_dau_tu_xdcb",
    "base_name": "nguon_von_dau_tu_xdcb",
    "was_conflict": False,
    "was_standardized": False,
  },
  "115": {
    "original_vi": "- LNST chưa phân phối lũy kế đến cuối kỳ trước",
    "original_en": "- Accumulated retained earning at the end of the previous period",
    "snake_case": "lnst_chua_phan_phoi_luy_ke_den_cuoi_ky_truoc",
    "base_name": "lnst_chua_phan_phoi_luy_ke_den_cuoi_ky_truoc",
    "was_conflict": False,
    "was_standardized": False,
  },
  "116": {
    "original_vi": "- LNST chưa phân phối kỳ này",
    "original_en": "- Undistributed earnings in this period",
    "snake_case": "lnst_chua_phan_phoi_ky_nay",
    "base_name": "lnst_chua_phan_phoi_ky_nay",
    "was_conflict": False,
    "was_standardized": False,
  },
  "113": {
    "original_vi": "10. Quỹ khác thuộc vốn chủ sở hữu",
    "original_en": "10. Other funds from owner's equity",
    "snake_case": "quy_khac_thuoc_von_chu_so_huu",
    "base_name": "quy_khac_thuoc_von_chu_so_huu",
    "was_conflict": False,
    "was_standardized": False,
  },
  "112": {
    "original_vi": "9. Quỹ hỗ trợ sắp xếp doanh nghiệp",
    "original_en": "9. Fund to support corporate restructuring",
    "snake_case": "quy_ho_tro_sap_xep_doanh_nghiep",
    "base_name": "quy_ho_tro_sap_xep_doanh_nghiep",
    "was_conflict": False,
    "was_standardized": False,
  },
  "111": {
    "original_vi": "8. Quỹ đầu tư phát triển",
    "original_en": "8. Investment and development fund",
    "snake_case": "quy_dau_tu_phat_trien",
    "base_name": "quy_dau_tu_phat_trien",
    "was_conflict": False,
    "was_standardized": False,
  },
  "110": {
    "original_vi": "7. Chênh lệch tỷ giá hối đoái",
    "original_en": "7. Foreign exchange differences",
    "snake_case": "chenh_lech_ty_gia_hoi_doai_110",
    "base_name": "chenh_lech_ty_gia_hoi_doai",
    "was_conflict": True,
    "was_standardized": False,
  },
  "109": {
    "original_vi": "6. Chênh lệch đánh giá lại tài sản",
    "original_en": "6. Assets revaluation differences",
    "snake_case": "chenh_lech_danh_gia_lai_tai_san_109",
    "base_name": "chenh_lech_danh_gia_lai_tai_san",
    "was_conflict": True,
    "was_standardized": False,
  },
  "108": {
    "original_vi": "5. Cổ phiếu quỹ (*)",
    "original_en": "5. Treasury shares",
    "snake_case": "treasury_shares",
    "base_name": "treasury_shares",
    "was_conflict": False,
    "was_standardized": False,
  },
  "114": {
    "original_vi": "11. Lợi nhuận sau thuế chưa phân phối",
    "original_en": "11. Undistributed earnings after tax",
    "snake_case": "loi_nhuan_sau_thue_chua_phan_phoi",
    "base_name": "loi_nhuan_sau_thue_chua_phan_phoi",
    "was_conflict": False,
    "was_standardized": False,
  },
  "132": {
    "original_vi": "13. Dự phòng bồi thường thiệt hại cho nhà đầu tư",
    "original_en": "13. Provision for investor's damage claims",
    "snake_case": "du_phong_boi_thuong_thiet_hai_cho_nha_dau_tu",
    "base_name": "du_phong_boi_thuong_thiet_hai_cho_nha_dau_tu",
    "was_conflict": False,
    "was_standardized": False,
  },
  "138": {
    "original_vi": "1.1. Vốn góp của chủ sở hữu",
    "original_en": "1.1. Capital from owners",
    "snake_case": "von_gop_cua_chu_so_huu",
    "base_name": "von_gop_cua_chu_so_huu",
    "was_conflict": False,
    "was_standardized": False,
  },
  "137": {
    "original_vi": "1. Vốn đầu tư của chủ sở hữu",
    "original_en": "1. Investment capital from owners",
    "snake_case": "von_dau_tu_cua_chu_so_huu",
    "base_name": "von_dau_tu_cua_chu_so_huu",
    "was_conflict": False,
    "was_standardized": False,
  },
  "136": {
    "original_vi": "I. Vốn chủ sở hữu",
    "original_en": "I. Owner's equity",
    "snake_case": "i_von_chu_so_huu",
    "base_name": "i_von_chu_so_huu",
    "was_conflict": False,
    "was_standardized": False,
  },
  "135": {
    "original_vi": "B. VỐN CHỦ SỞ HỮU (400=410+420)",
    "original_en": "B. OWNER'S EQUITY (400=410+420)",
    "snake_case": "b_von_chu_so_huu_400410420",
    "base_name": "b_von_chu_so_huu_400410420",
    "was_conflict": False,
    "was_standardized": False,
  },
  "134": {
    "original_vi": "15. Quỹ phát triển khoa học và công nghệ",
    "original_en": "15. Fund for technology development",
    "snake_case": "quy_phat_trien_khoa_hoc_va_cong_nghe",
    "base_name": "quy_phat_trien_khoa_hoc_va_cong_nghe",
    "was_conflict": False,
    "was_standardized": False,
  },
  "133": {
    "original_vi": "14. Thuế thu nhập hoãn lại phải trả",
    "original_en": "14. Deferred income tax liabilities",
    "snake_case": "thue_thu_nhap_hoan_lai_phai_tra",
    "base_name": "thue_thu_nhap_hoan_lai_phai_tra",
    "was_conflict": False,
    "was_standardized": False,
  },
  "131": {
    "original_vi": "12. Dự phòng phải trả dài hạn",
    "original_en": "12. Provision for long-term liabilities",
    "snake_case": "du_phong_phai_tra_dai_han",
    "base_name": "du_phong_phai_tra_dai_han",
    "was_conflict": False,
    "was_standardized": False,
  },
  "130": {
    "original_vi": "Dự phòng trợ cấp mất việc làm",
    "original_en": "Provision for severance allowances",
    "snake_case": "du_phong_tro_cap_mat_viec_lam",
    "base_name": "du_phong_tro_cap_mat_viec_lam",
    "was_conflict": False,
    "was_standardized": False,
  },
  "129": {
    "original_vi": "Vốn nhận ủy thác đầu tư dài hạn",
    "original_en": "Funds received from trust investors",
    "snake_case": "von_nhan_uy_thac_dau_tu_dai_han",
    "base_name": "von_nhan_uy_thac_dau_tu_dai_han",
    "was_conflict": False,
    "was_standardized": False,
  },
  "128": {
    "original_vi": "11. Phải trả, phải nộp khác dài hạn",
    "original_en": "11. Other long-term liabilities",
    "snake_case": "phai_tra_phai_nop_khac_dai_han",
    "base_name": "phai_tra_phai_nop_khac_dai_han",
    "was_conflict": False,
    "was_standardized": False,
  },
  "127": {
    "original_vi": "10. Nhận ký quỹ, ký cược dài hạn",
    "original_en": "10. Long-term deposits, collateral received",
    "snake_case": "nhan_ky_quy_ky_cuoc_dai_han",
    "base_name": "nhan_ky_quy_ky_cuoc_dai_han",
    "was_conflict": False,
    "was_standardized": False,
  },
  "126": {
    "original_vi": "9. Doanh thu chưa thực hiện dài hạn",
    "original_en": "9. Unearned revenue",
    "snake_case": "doanh_thu_chua_thuc_hien_dai_han",
    "base_name": "doanh_thu_chua_thuc_hien_dai_han",
    "was_conflict": False,
    "was_standardized": False,
  },
  "125": {
    "original_vi": "8. Phải trả nội bộ dài hạn",
    "original_en": "8. Long-term inter-company payables",
    "snake_case": "phai_tra_noi_bo_dai_han",
    "base_name": "phai_tra_noi_bo_dai_han",
    "was_conflict": False,
    "was_standardized": False,
  },
  "157": {
    "original_vi": "II. Nguồn kinh phí và quỹ khác",
    "original_en": "II. Budget resources and other funds ",
    "snake_case": "ii_nguon_kinh_phi_va_quy_khac_157",
    "base_name": "ii_nguon_kinh_phi_va_quy_khac",
    "was_conflict": True,
    "was_standardized": False,
  },
  "153": {
    "original_vi": "7.2. Lợi nhuận chưa thực hiện",
    "original_en": "7.2. Unrealised losses",
    "snake_case": "loi_nhuan_chua_thuc_hien",
    "base_name": "loi_nhuan_chua_thuc_hien",
    "was_conflict": False,
    "was_standardized": False,
  },
  "154": {
    "original_vi": "Nguồn vốn đầu tư XDCB",
    "original_en": "Reserves for investment in construction",
    "snake_case": "nguon_von_dau_tu_xdcb_154",
    "base_name": "nguon_von_dau_tu_xdcb",
    "was_conflict": True,
    "was_standardized": False,
  },
  "155": {
    "original_vi": "Quỹ hỗ trợ sắp xếp doanh nghiệp",
    "original_en": "Fund to support corporate restructuring",
    "snake_case": "quy_ho_tro_sap_xep_doanh_nghiep_155",
    "base_name": "quy_ho_tro_sap_xep_doanh_nghiep",
    "was_conflict": True,
    "was_standardized": False,
  },
  "156": {
    "original_vi": "8. Lợi ích cổ đông không nắm quyền kiểm soát",
    "original_en": "8. Minority interest",
    "snake_case": "loi_ich_co_dong_khong_nam_quyen_kiem_soat",
    "base_name": "loi_ich_co_dong_khong_nam_quyen_kiem_soat",
    "was_conflict": False,
    "was_standardized": False,
  },
  "160": {
    "original_vi": "TỔNG CỘNG NGUỒN VỐN  (440=300+400)",
    "original_en": "TOTAL OWNER'S EQUITY AND LIABILITIES",
    "snake_case": "tong_cong_nguon_von_440300400",
    "base_name": "tong_cong_nguon_von_440300400",
    "was_conflict": False,
    "was_standardized": False,
  },
  "158": {
    "original_vi": "1. Nguồn kinh phí",
    "original_en": "1. Subsidized not-for-profit funds",
    "snake_case": "nguon_kinh_phi_158",
    "base_name": "nguon_kinh_phi",
    "was_conflict": True,
    "was_standardized": False,
  },
  "159": {
    "original_vi": "2. Nguồn kinh phí đã hình thành TSCĐ",
    "original_en": "2. Funds invested in fixed assets",
    "snake_case": "nguon_kinh_phi_da_hinh_thanh_tscd_159",
    "base_name": "nguon_kinh_phi_da_hinh_thanh_tscd",
    "was_conflict": True,
    "was_standardized": False,
  },
  "151": {
    "original_vi": "7. Lợi nhuận sau thuế chưa phân phối",
    "original_en": "7. Undistributed earnings after tax",
    "snake_case": "loi_nhuan_sau_thue_chua_phan_phoi_151",
    "base_name": "loi_nhuan_sau_thue_chua_phan_phoi",
    "was_conflict": True,
    "was_standardized": False,
  },
  "161": {
    "original_vi": "LỢI NHUẬN ĐÃ PHÂN PHỐI CHO NHÀ ĐẦU TƯ",
    "original_en": "Realised profits for investor",
    "snake_case": "loi_nhuan_da_phan_phoi_cho_nha_dau_tu",
    "base_name": "loi_nhuan_da_phan_phoi_cho_nha_dau_tu",
    "was_conflict": False,
    "was_standardized": False,
  },
  "152": {
    "original_vi": "7.1. Lợi nhuận đã thực hiện",
    "original_en": "7.1. Realised profits",
    "snake_case": "loi_nhuan_da_thuc_hien",
    "base_name": "loi_nhuan_da_thuc_hien",
    "was_conflict": False,
    "was_standardized": False,
  },
  "140": {
    "original_vi": "b. Cổ phiếu ưu đãi",
    "original_en": "b. Preferred stock",
    "snake_case": "b_co_phieu_uu_dai",
    "base_name": "b_co_phieu_uu_dai",
    "was_conflict": False,
    "was_standardized": False,
  },
  "150": {
    "original_vi": "6. Quỹ khác thuộc vốn chủ sở hữu",
    "original_en": "6. Other funds from owner's equity",
    "snake_case": "quy_khac_thuoc_von_chu_so_huu_150",
    "base_name": "quy_khac_thuoc_von_chu_so_huu",
    "was_conflict": True,
    "was_standardized": False,
  },
  "149": {
    "original_vi": "5. Quỹ dự phòng tài chính và rủi ro nghề nghiệp",
    "original_en": "5. Financial reserves",
    "snake_case": "quy_du_phong_tai_chinh_va_rui_ro_nghe_nghiep",
    "base_name": "quy_du_phong_tai_chinh_va_rui_ro_nghe_nghiep",
    "was_conflict": False,
    "was_standardized": False,
  },
  "148": {
    "original_vi": "Quỹ đầu tư phát triển",
    "original_en": "Investment and development fund",
    "snake_case": "quy_dau_tu_phat_trien_148",
    "base_name": "quy_dau_tu_phat_trien",
    "was_conflict": True,
    "was_standardized": False,
  },
  "147": {
    "original_vi": "4. Quỹ dự trữ điều lệ",
    "original_en": "4. Supplementary capital reserve",
    "snake_case": "quy_du_tru_dieu_le",
    "base_name": "quy_du_tru_dieu_le",
    "was_conflict": False,
    "was_standardized": False,
  },
  "146": {
    "original_vi": "3. Chênh lệch tỷ giá hối đoái",
    "original_en": "3. Foreign exchange differences",
    "snake_case": "chenh_lech_ty_gia_hoi_doai_146",
    "base_name": "chenh_lech_ty_gia_hoi_doai",
    "was_conflict": True,
    "was_standardized": False,
  },
  "145": {
    "original_vi": "2. Chênh lệch đánh giá lại tài sản theo giá trị hợp lý",
    "original_en": "2. Assets revaluation differences",
    "snake_case": "chenh_lech_danh_gia_lai_tai_san_theo_gia_tri_hop_ly",
    "base_name": "chenh_lech_danh_gia_lai_tai_san_theo_gia_tri_hop_ly",
    "was_conflict": False,
    "was_standardized": False,
  },
  "144": {
    "original_vi": "1.5. Cổ phiếu quỹ",
    "original_en": "1.5. Treasury shares",
    "snake_case": "treasury_shares_144",
    "base_name": "treasury_shares",
    "was_conflict": True,
    "was_standardized": False,
  },
  "143": {
    "original_vi": "1.4. Vốn khác của chủ sở hữu",
    "original_en": "1.4. Other capital of Owners",
    "snake_case": "von_khac_cua_chu_so_huu",
    "base_name": "von_khac_cua_chu_so_huu",
    "was_conflict": False,
    "was_standardized": False,
  },
  "142": {
    "original_vi": "1.3. Quyền chọn chuyển đổi trái phiếu",
    "original_en": "1.3 Conversion options on convertible bonds",
    "snake_case": "quyen_chon_chuyen_doi_trai_phieu",
    "base_name": "quyen_chon_chuyen_doi_trai_phieu",
    "was_conflict": False,
    "was_standardized": False,
  },
  "141": {
    "original_vi": "1.2. Thặng dư vốn cổ phần",
    "original_en": "1.2. Share premium",
    "snake_case": "thang_du_von_co_phan",
    "base_name": "thang_du_von_co_phan",
    "was_conflict": False,
    "was_standardized": False,
  },
  "139": {
    "original_vi": "a. Cổ phiếu phổ thông",
    "original_en": "a. Common stock",
    "snake_case": "a_co_phieu_pho_thong",
    "base_name": "a_co_phieu_pho_thong",
    "was_conflict": False,
    "was_standardized": False,
  },
  "162": {
    "original_vi": "1. Lợi nhuận đã phân phối cho Nhà đầu tư trong năm",
    "original_en": "1. Realised profits for investor in the year",
    "snake_case": "loi_nhuan_da_phan_phoi_cho_nha_dau_tu_trong_nam",
    "base_name": "loi_nhuan_da_phan_phoi_cho_nha_dau_tu_trong_nam",
    "was_conflict": False,
    "was_standardized": False,
  },
}
